import json
from pathlib import Path

import polars as pl

PROJECT_ROOT = Path(__file__).resolve().parent.parent
WEIGHTS_PATH = PROJECT_ROOT / "data" / "situational_weights.json"

# ---------------------------------------------------------------------
# LEGACY (Phase 6) -- kept for reference, no longer the live source.
#
# These were hand-copied out of a notebook and are the reason for the
# Phase 7 complaint that every adjustment came out negative. They are
# the SLOPES of a regression that also had a constant term, but the
# constant was never transcribed. Since workload_share and experience
# are always-positive features carrying negative slopes, dropping a
# positive intercept forces every adjustment negative -- RB by 3.59,
# WR by 2.37, TE by 1.58, uniformly and for no statistical reason. That
# alone erased 23 of the 29 skill players who cleared 15 PPG on the raw
# baseline, and inflated rookies (who take no adjustment at all) against
# veterans who were absorbing a penalty that did not exist.
#
# Live weights now come from data/situational_weights.json, generated by
# src/fit_weights.py, where intercept and slopes cannot be separated.
# Retained here only as the documented fallback below.
# ---------------------------------------------------------------------
LEGACY_SITUATIONAL_WEIGHTS = {
    "RB": {"continuity_score": -0.9493, "workload_share": -3.4441, "experience": -0.4674},
    "WR": {"team_changed": -0.8667, "workload_share": -7.1708, "recent_major_injury": -1.8642, "experience": -0.3873},
    "TE": {"workload_share": -7.5826, "experience": -0.1898},
}

# Intercepts recovered by refitting data/backtest_features.csv with a
# constant term (see src/fit_weights.py). Only used by the fallback path.
LEGACY_INTERCEPTS = {"RB": 3.5925, "WR": 2.3653, "TE": 1.5764}


def load_situational_weights(path=WEIGHTS_PATH):
    """
    Loads the fitted weights written by src/fit_weights.py.

    Falls back to the LEGACY_* constants above if the JSON is missing,
    so the pipeline still runs on a fresh clone before fit_weights has
    been executed -- but it prints a warning, because the fallback has
    no feature_means and therefore imputes missing values less well.

    Returns: {position: {"intercept": float, "weights": {...},
                         "feature_means": {...}}}
    """
    if not path.exists():
        print(f"WARNING: {path} not found -- falling back to LEGACY weights. "
              f"Run `python -m src.fit_weights` to regenerate.")
        return {
            position: {
                "intercept": LEGACY_INTERCEPTS[position],
                "weights": weights,
                "feature_means": {},
            }
            for position, weights in LEGACY_SITUATIONAL_WEIGHTS.items()
        }

    with open(path) as f:
        return json.load(f)["positions"]


def apply_situational_weights(player_features, weights_by_position=None):
    """
    Adds `adjusted_fantasy_points_per_game` on top of the pure
    statistical `fantasy_points_per_game` baseline.

    For each position the adjustment is:

        intercept + sum(feature_value * weight)

    The intercept is not optional. The underlying regression models
    `delta` -- actual PPG minus the player's own trailing 3-year
    baseline -- so the constant is the model's honest expectation for a
    player whose features are all zero. Omitting it asserts such a
    player would exactly repeat his baseline, which the data does not
    say, and biases every prediction by a fixed amount.

    Missing feature values are imputed with the position's mean from the
    fitting sample rather than 0, so a null means "treat as an average
    player at this position." Filling with 0 would hand the player the
    full positive intercept while dodging the negative usage/experience
    terms -- an unearned boost, concentrated in players whose
    workload_share is deliberately nulled out (everyone who changed
    teams; see situational.py).

    Positions absent from the weights dict -- currently QB, K, DST --
    pass through with zero adjustment. For QB that is a real finding:
    nothing tested significant across every Phase 5-6 specification.

    Rookies (`is_rookie`) still take no adjustment. Every weight was
    estimated from veteran deltas against a player's OWN history, and a
    rookie's baseline is a cohort projection, not personal history, so
    these coefficients were never validated on that population. It also
    sidesteps data artifacts that only appear for rookies: `team_changed`
    compares this season's team to last season's roster, which a rookie
    was never on, so it reads "changed" for nearly every rookie
    regardless of situation. Phase 12 replaces this with a rookie-specific
    model fit on the 2021-25 classes.
    """
    if weights_by_position is None:
        weights_by_position = load_situational_weights()

    adjustment = pl.lit(0.0)

    for position, spec in weights_by_position.items():
        position_adjustment = pl.lit(float(spec["intercept"]))
        feature_means = spec.get("feature_means", {})

        for feature, weight in spec["weights"].items():
            # Booleans arrive from CSV as true/false strings or as bools
            # depending on the read path; cast through Float64 so either
            # works and the arithmetic below is well-defined.
            value = pl.col(feature).cast(pl.Float64)
            fill_value = feature_means.get(feature, 0.0)
            position_adjustment = position_adjustment + value.fill_null(fill_value) * weight

        adjustment = (
            pl.when(pl.col("position") == position)
            .then(position_adjustment)
            .otherwise(adjustment)
        )

    adjustment = pl.when(pl.col("is_rookie")).then(0.0).otherwise(adjustment)

    return player_features.with_columns([
        (pl.col("fantasy_points_per_game") + adjustment).alias(
            "adjusted_fantasy_points_per_game"
        ),
        # Exposed so the draft board can show WHY a player moved, and so
        # a sanity check can confirm the adjustment is two-sided rather
        # than uniformly negative.
        adjustment.alias("situational_adjustment"),
    ])
