import json
from pathlib import Path

import polars as pl

PROJECT_ROOT = Path(__file__).resolve().parent.parent
WEIGHTS_PATH = PROJECT_ROOT / "data" / "situational_weights.json"
ROOKIE_WEIGHTS_PATH = PROJECT_ROOT / "data" / "rookie_weights.json"

# ---------------------------------------------------------------------
# LEGACY (Phase 6) -- kept for reference, no longer the live source.
#
# These were hand-copied out of a notebook and are the reason for the
# Phase 7 complaint that every adjustment came out negative. They are
# the SLOPES of a regression that also had a constant term, but the
# constant was never transcribed. Since workload_share and experience
# are always-positive features carrying negative slopes, dropping a
# positive intercept forces every adjustment negative -- RB by 3.59,
# WR by 2.37, TE by 1.58, uniformly and for no statistical reason. That
# alone erased 23 of the 29 skill players who cleared 15 PPG on the raw
# baseline, and inflated rookies (who take no adjustment at all) against
# veterans who were absorbing a penalty that did not exist.
#
# Live weights now come from data/situational_weights.json, generated by
# src/fit_weights.py, where intercept and slopes cannot be separated.
# Retained here only as the documented fallback below.
# ---------------------------------------------------------------------
LEGACY_SITUATIONAL_WEIGHTS = {
    "RB": {"continuity_score": -0.9493, "workload_share": -3.4441, "experience": -0.4674},
    "WR": {"team_changed": -0.8667, "workload_share": -7.1708, "recent_major_injury": -1.8642, "experience": -0.3873},
    "TE": {"workload_share": -7.5826, "experience": -0.1898},
}

# Intercepts recovered by refitting data/backtest_features.csv with a
# constant term (see src/fit_weights.py). Only used by the fallback path.
LEGACY_INTERCEPTS = {"RB": 3.5925, "WR": 2.3653, "TE": 1.5764}


def load_situational_weights(path=WEIGHTS_PATH):
    """
    Loads the fitted weights written by src/fit_weights.py.

    Falls back to the LEGACY_* constants above if the JSON is missing,
    so the pipeline still runs on a fresh clone before fit_weights has
    been executed -- but it prints a warning, because the fallback has
    no feature_means and therefore imputes missing values less well.

    Returns: {position: {"intercept": float, "weights": {...},
                         "feature_means": {...}}}
    """
    if not path.exists():
        print(f"WARNING: {path} not found -- falling back to LEGACY weights. "
              f"Run `python -m src.fit_weights` to regenerate.")
        return {
            position: {
                "intercept": LEGACY_INTERCEPTS[position],
                "weights": weights,
                "feature_means": {},
            }
            for position, weights in LEGACY_SITUATIONAL_WEIGHTS.items()
        }

    with open(path) as f:
        return json.load(f)["positions"]


INJURY_OVERRIDES_PATH = PROJECT_ROOT / "injury_overrides.csv"

# Features that describe a player's SITUATION rather than the player.
# Nulled for anyone marked FREE_AGENT, so apply_situational_weights
# imputes them to the position mean -- which is what "no opinion" should
# mean.
#
# WHY THIS EXISTS (Aug 6). Brandon Aiyuk is unsigned and the model ranked
# him as though rostered: `latest_team` still names his old club, so
# `team_changed` read "same team", `workload_share` read his old usage,
# and `position_competition_ppg` measured teammates he no longer has.
# Every one of those is a confident statement about a situation that does
# not exist.
#
# What survives is everything true of the PLAYER wherever he signs: age,
# injury history, his own usage trajectory. A 28-year-old coming off IR
# is a 28-year-old coming off IR whoever employs him in September.
#
# NOT the same as OUT_SEASON. An unsigned player will most likely play;
# the model just cannot say where. Marking him out would be a lie in the
# other direction and would hide him from the board entirely.
FREE_AGENT_NULLED_FEATURES = [
    "workload_share",
    "position_competition_ppg",
    "position_competition_top1",
    "position_competition_top2",
    "position_competition_top3",
    "pos_rank",
    "depth_chart_missing",
    "team_changed",
    "pass_att_pg",
    "rush_att_pg",
    "returning_oline_starters",
    "qb_changed",
    "coach_changed",
]


def apply_free_agents(player_features, path=INJURY_OVERRIDES_PATH):
    """
    Blanks team-dependent features for players marked FREE_AGENT in
    injury_overrides.csv.

    CALLED FROM pipeline.py, BEFORE apply_situational_weights, and that
    placement is the whole point. The adjustment is computed in the
    pipeline and written into player_features.csv; blanking a feature in
    build_board afterwards would change a column nothing reads again. I
    put it there first and it would have done exactly nothing.

    Rides on injury_overrides.csv rather than a new file: both are
    hand-maintained facts no feed can see, and one file to update before
    a draft beats two to forget.

    `team` itself is deliberately LEFT ALONE. Nulling it would fail the
    "everyone has a team" sanity check and break joins keyed on it, for
    no gain -- what matters is that no team-derived NUMBER reaches the
    projection, and nulling the features achieves that directly.
    """
    if not path.exists():
        return player_features

    overrides = pl.read_csv(path)
    if "status" not in overrides.columns:
        return player_features

    names = set(
        overrides.filter(
            pl.col("status").cast(pl.String).str.to_uppercase() == "FREE_AGENT"
        ).select("player_name").to_series().to_list()
    )
    if not names:
        return player_features

    is_free_agent = pl.col("player_name").is_in(list(names))
    present = [c for c in FREE_AGENT_NULLED_FEATURES if c in player_features.columns]

    player_features = player_features.with_columns([
        pl.when(is_free_agent).then(None).otherwise(pl.col(c)).alias(c)
        for c in present
    ])

    matched = player_features.filter(is_free_agent).select("player_name").to_series().to_list()
    print(f"Free agents: {len(matched)} of {len(names)} listed matched; "
          f"{len(present)} team-derived features blanked")
    for name in matched:
        print(f"   {name}: age and injury history still apply, team context "
              f"set to no-opinion")
    missing = names - set(matched)
    if missing:
        print(f"   WARNING: nothing matched {sorted(missing)}. Check the spelling "
              f"against player_features.csv -- an unmatched override is silent.")

    return player_features


def load_rookie_weights(path=ROOKIE_WEIGHTS_PATH):
    """
    Phase 12. Loads the rookie weights written by
    src/fit_rookie_weights.py, keeping only the positions whose fit met
    the bar.

    THE FILTER IS THE POINT. fit_rookie_weights records
    `fit_is_trustworthy` per position -- something cleared alpha AND
    nothing flipped sign across the five leave-one-class-out folds --
    and this function silently drops the rest. A position that fails
    falls back to the flat cohort baseline, which is exactly what it had
    before Phase 12, so failure costs nothing and shipping a fragile
    coefficient would.

    Returns {} if the file is absent, which is the correct behaviour on
    a clone that has not run the rookie fit: rookies take no adjustment,
    same as Phase 11.
    """
    if not path.exists():
        return {}

    with open(path) as f:
        payload = json.load(f)

    positions = payload.get("positions", {})
    trusted = {p: s for p, s in positions.items() if s.get("fit_is_trustworthy")}

    rejected = sorted(set(positions) - set(trusted))
    if rejected:
        print(f"Rookie weights: {rejected} did not meet the stability bar -- "
              f"those positions keep the flat cohort baseline.")
    if trusted:
        print(f"Rookie weights active at: {sorted(trusted)}")

    return trusted


def _position_adjustment(spec):
    """
    Builds the `intercept + sum(feature x weight)` expression for one
    position, with mean-imputation and centering applied in that order.

    Shared by the veteran and rookie paths because the arithmetic is
    identical and the ways it goes wrong are the ways this project has
    already gone wrong twice -- a coefficient separated from its
    intercept (Phase 6) or from its center (nearly, Phase 10). One
    implementation means one place for that to be right.

    Order matters: fill first, then center. Filling with the raw mean
    and then centering yields exactly 0 -- "no opinion" -- which is the
    intended fallback for a missing value.
    """
    expression = pl.lit(float(spec["intercept"]))
    feature_means = spec.get("feature_means", {})
    centers = spec.get("centers", {})

    for feature, weight in spec["weights"].items():
        # Booleans arrive from CSV as true/false strings or as bools
        # depending on the read path; cast through Float64 so either
        # works and the arithmetic below is well-defined.
        value = pl.col(feature).cast(pl.Float64)
        value = value.fill_null(feature_means.get(feature, 0.0))
        if feature in centers:
            value = value - float(centers[feature])
        expression = expression + value * weight

    return expression


def apply_situational_weights(player_features, weights_by_position=None):
    """
    Adds `adjusted_fantasy_points_per_game` on top of the pure
    statistical `fantasy_points_per_game` baseline.

    For each position the adjustment is:

        intercept + sum(feature_value * weight)

    The intercept is not optional. The underlying regression models
    `delta` -- actual PPG minus the player's own trailing 3-year
    baseline -- so the constant is the model's honest expectation for a
    player whose features are all zero. Omitting it asserts such a
    player would exactly repeat his baseline, which the data does not
    say, and biases every prediction by a fixed amount.

    Missing feature values are imputed with the position's mean from the
    fitting sample rather than 0, so a null means "treat as an average
    player at this position." Filling with 0 would hand the player the
    full positive intercept while dodging the negative usage/experience
    terms -- an unearned boost, concentrated in players whose
    workload_share is deliberately nulled out (everyone who changed
    teams; see situational.py).

    Positions absent from the weights dict -- currently K and DST --
    pass through with zero adjustment.

    QB was in that list from Phase 5 until Phase 10, when widening the
    training window to 2021-2025 finally gave it enough
    quarterback-seasons for age to register (-0.19 PPG per year,
    p=0.020, n=157 against 96 before). It is the only QB weight; every
    other candidate is still dead on the wider sample. Worth
    remembering that the long-standing "nothing works for QB" result was
    partly a statement about sample size, not only about quarterbacks.

    Rookies (`is_rookie`) never take a VETERAN adjustment, and that has
    not changed. Every weight above was estimated from veteran deltas
    against a player's OWN history; a rookie's baseline is a cohort
    projection, so these coefficients were never validated on that
    population. It also sidesteps artifacts that only appear for rookies
    -- `team_changed` compares this season's team to last season's
    roster, which a rookie was never on, so it reads "changed" for
    essentially every rookie regardless of situation.

    PHASE 12 changed what they get INSTEAD. Rookies now take the rookie
    model from data/rookie_weights.json -- fitted on the 2021-25 classes
    against a leave-one-class-out cohort baseline, using only features
    knowable before a player takes a snap. Positions whose fit failed
    the stability bar, and a missing weights file, both fall back to a
    zero adjustment, which is exactly the Phase 11 behaviour. So this
    can only ever add information; it cannot silently remove any.
    """
    if weights_by_position is None:
        weights_by_position = load_situational_weights()

    # Phase 11 B (CP5). The adjustment sits on top of the SHRUNK baseline
    # when one is present, because that is the baseline the weights were
    # fitted against. Falls back to the raw column so an older
    # player_features.csv still loads rather than failing on a missing
    # column -- but the two must not be mixed, which is why
    # verify_adjustments checks that the shrunk column exists.
    baseline_column = (
        "fantasy_points_per_game_shrunk"
        if "fantasy_points_per_game_shrunk" in player_features.columns
        else "fantasy_points_per_game"
    )

    # Centered features were fitted as deviations from the position
    # mean, so _position_adjustment() shifts them by the SAME center
    # before multiplying. Applying a centered age coefficient to a raw
    # age is wrong by coef x center -- about -9.5 PPG at RB, which would
    # dwarf every real adjustment in the model. That is the Phase 6
    # intercept bug in a different costume, which is why the center ships
    # inside the same JSON object as the weight rather than living as a
    # constant in this file.
    adjustment = pl.lit(0.0)
    for position, spec in weights_by_position.items():
        adjustment = (
            pl.when(pl.col("position") == position)
            .then(_position_adjustment(spec))
            .otherwise(adjustment)
        )

    # PHASE 12. Rookies leave the veteran path entirely and take the
    # rookie model instead -- a different fit, on a different population,
    # against a different baseline. A position with no trusted rookie fit
    # falls through to 0.0, which is the pre-Phase-12 behaviour.
    #
    # The `is_rookie` branch is evaluated LAST and unconditionally, so a
    # rookie can never pick up a veteran coefficient by accident even if
    # he happens to carry a non-null value in a veteran-only feature.
    rookie_weights = load_rookie_weights()
    rookie_adjustment = pl.lit(0.0)
    for position, spec in rookie_weights.items():
        rookie_adjustment = (
            pl.when(pl.col("position") == position)
            .then(_position_adjustment(spec))
            .otherwise(rookie_adjustment)
        )

    adjustment = (
        pl.when(pl.col("is_rookie"))
        .then(rookie_adjustment)
        .otherwise(adjustment)
    )

    return player_features.with_columns([
        (pl.col(baseline_column) + adjustment).alias(
            "adjusted_fantasy_points_per_game"
        ),
        # Exposed so the draft board can show WHY a player moved, and so
        # a sanity check can confirm the adjustment is two-sided rather
        # than uniformly negative.
        adjustment.alias("situational_adjustment"),
    ])
